if not CLIENT then return end

hook.Add("PopulateToolMenu","TRM_weapon_base_q_menu",function()
    spawnmenu.AddToolMenuOption("TriggerMiku_Work","WeaponBase","trmbase_admin","Admin","","",function(panel)
        panel:ClearControls()
        panel:CheckBox(language.GetPhrase("TRMBase_InfiniteAmmo"),"trmbase_infinite_ammo")
        panel:CheckBox(language.GetPhrase("TRMBase_AutoReload"),"trmbase_autoreload")
        panel:CheckBox(language.GetPhrase("TRMBase_FireInteruptReload"),"trmbase_fire_interupt_reload")
        panel:CheckBox(language.GetPhrase("TRMBase_SprintReload"),"trmbase_allow_sprintreload")
        panel:CheckBox(language.GetPhrase("TRMBase_LoadAttOnPickup"),"trmbase_load_attachment_on_pickup")
    end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work","WeaponBase","trmbase_npc","NPC","","",function(panel)
        panel:ClearControls()
        panel:CheckBox(language.GetPhrase("TRMBase_ReplaceNPC"),"trmbase_replace_npc")
        panel:CheckBox(language.GetPhrase("TRMBase_ReplaceWeapon"),"trmbase_replace_weapon")
        panel:NumSlider(language.GetPhrase("TRMBase_ReplaceChance"),"trmbase_replace_chance",0,100,0)
        panel:CheckBox(language.GetPhrase("TRMBase_RandomAttach"),"trmbase_random_attachments")
    end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work","WeaponBase","trmbase_client","Client","","",function(panel)
        panel:ClearControls()
        panel:KeyBinder(language.GetPhrase("TRMBase_MeleeKey"),"trmbase_cl_keybind_melee")
        panel:KeyBinder(language.GetPhrase("TRMBase_InspectKey"),"trmbase_cl_keybind_inspect")
        panel:KeyBinder(language.GetPhrase("TRMBase_CustomizeKey"),"trmbase_cl_keybind_customize")
        panel:CheckBox(language.GetPhrase("TRMBase_Crosshair"),"trmbase_crosshair_enable")
        panel:ColorPicker(language.GetPhrase("TRMBase_CrosshairColor"),"trmbase_crosshair_color_r","trmbase_crosshair_color_g","trmbase_crosshair_color_b","trmbase_crosshair_color_a")
        panel:NumSlider(language.GetPhrase("TRMBase_CrosshairStyle"),"trmbase_crosshair_style",1,3,0)
        panel:CheckBox(language.GetPhrase("TRMBase_CrosshairDot"),"trmbase_crosshair_dot")
        panel:CheckBox(language.GetPhrase("TRMBase_HideHUDInspect"),"trmbase_hidehud_inspect")
    end)
    spawnmenu.AddToolMenuOption("TriggerMiku_Work","WeaponBase","trmbase_develop","Develop","","",function(panel)
        panel:ClearControls()
        panel:CheckBox("冻结 VM (Freeze VM)","trmbase_freeze_vm")
    end)
end)